image:
  file: .gitpod.Dockerfile

tasks:
  - name: Taskord Server
    init: >
      cp .env.gitpod .env &&
      composer install &&
      npm install &&
      php artisan key:generate &&
      php artisan migrate:fresh --seed
    command: >
      npm run dev
