image:
  file: .gitpod.Dockerfile

tasks:
  - name: Taskord Server
    init: >
        cp .env.example .env &&
        composer install &&
        npm install &&
        php artisan key:generate
    command: >
      npm run dev
