{{ route('patron.home') }}
{{ route('about') }}
{{ route('reputation') }}
{{ route('terms') }}
{{ route('privacy') }}
{{ route('security') }}
{{ route('sponsors') }}
{{ route('deals') }}
{{ route('open') }}