version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'dependency'
      prefix-development: 'development-dependency'
    assignees:
      - yo
    reviewers:
      - yo
    open-pull-requests-limit: 200
    rebase-strategy: auto

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'dependency'
      prefix-development: 'development-dependency'
    assignees:
      - yo
    reviewers:
      - yo
    open-pull-requests-limit: 200
    rebase-strategy: auto
