name: Brew

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Brew
    runs-on: macos-latest
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v2

    - name: 📦 Brew bundle
      run: brew bundle
